[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"
  [[headers]]
    for = "/static/*"
    [headers.values]
    Cache-Control = "public, max-age=360000"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
